hash-format = "sha256"

[[files]]
file = "mods/Axiom-5.2.1-for-MC1.20.1.jar"
hash = "84acaaaf8b4f172249e365886eb56fcc47b99417e4bf11bcbe0e9722af1f3d04"

[[files]]
file = "mods/CopperandTuffBackport-1.2.jar"
hash = "a03163616eeafcac5a51c5aa1c79285fe0b87ad0b84b2d90d7ca4dbeeea9dc7e"

[[files]]
file = "mods/CustomNPCs-Unofficial-Fabric-1.20.1.20240901.jar"
hash = "f31eeae426a19f297ac6062aefbb1932be111cf60d78b17eaf533043cd9fb8cb"

[[files]]
file = "mods/DistantHorizons-2.2.1-a-1.20.1-forge-fabric.jar"
hash = "f282957cb0112f4cf2ce0feb0ecac73d388fab2896b8d11c53d724f4d728d863"

[[files]]
file = "mods/FILTERSAPI-FABRIC-1.0.0+1.20.1.jar"
hash = "c575b488d749ee9cee3bf88ed45159cf8930518e363607e368b69f86628f58e0"

[[files]]
file = "mods/FarmersDelight-1.20.1-2.1.6+refabricated.jar"
hash = "39a1cb413075e8e33c73849dd68ef2b58f8dfdd4e55adcdc9f13419dce81e6dc"

[[files]]
file = "mods/Farmersrespite-Fabric-3.0.2.jar"
hash = "6bc6a60d18db20428fa0500f9c6d94d91cfb04a77a154d0b18f8fa53b39588ae"

[[files]]
file = "mods/ImmediatelyFast-Fabric-1.3.3+1.20.4.jar"
hash = "095105939d690664a8f5411ffbf54e7eeaa064f574963395c30e076468a44ccb"

[[files]]
file = "mods/JCM-2.0.0-prerelease.1+1.20.1.jar"
hash = "f41b213a018aecefaca20e6a4dd4cff7d52bac80841fb0810edcefe4bbf691cd"

[[files]]
file = "mods/MSD-fabric-1.20.1-4.0.0-prerelease.1-1.3.18.jar"
hash = "d239562461eae65edf1a20f54d586b56da56b636bebd617b3b637eb6199ea673"

[[files]]
file = "mods/MSD-fabric-1.20.4-4.0.0-prerelease.1-1.3.18.jar"
hash = "35bbbac3eb82ac5296959a5c4d1f2ec3401515bee1d756cfe076b7fd8397529d"

[[files]]
file = "mods/MTR-London-Underground-Addon-fabric-2.2.3+1.20.1.jar"
hash = "1337b26268da7ddf8ffe40d2d21f9d50cd4541ec1a57348be991e95e1fbc87a5"

[[files]]
file = "mods/MTR-Russian-Metro-Addon-fabric-4.0.0-2.0.0-beta-4+1.20.1.jar"
hash = "e4c88ecb10465ee0c340cc6d5f0b48a30cbc89f0a0ce157a06b094fe3f756235"

[[files]]
file = "mods/MTR-fabric-4.0.0-prerelease.2+1.20.1.jar"
hash = "e498d6f5662e45b1db4390b8c1fd7edc02aa82eb43237586faea0591dabf7c32"

[[files]]
file = "mods/Patchouli-1.20.1-81-FABRIC.jar"
hash = "80271bc401f716ada590047755cf5b455e97417e61e1fbf1ba94ccb45f0015b3"

[[files]]
file = "mods/Platform-fabric-1.20.1-1.2.10.1.jar"
hash = "6979467caa916c7458b3b5bf6c32e062378575ec9b1d1ce7b9d8480703fa51a8"

[[files]]
file = "mods/Rocket-Launcher-Mod-Fabric-1.20.4.jar"
hash = "b347e0292d307f8ad2646c1d7a4a935a92c59362a3b57e8ff2e0ede89c21a9b6"

[[files]]
file = "mods/Slideshow-fabric-1.20.1-1.0.3-Enhancement-1.jar"
hash = "774ecae8c258a86c7dc69b290945a8a01a5d8f3315a1caa7e2d8e4c4e299985c"

[[files]]
file = "mods/TerraBlender-fabric-1.20.1-3.0.1.10.jar"
hash = "d02d9aa2ccf091264b0fcef07644128b823b3421a02bfc40391a01aa1ccd0a24"

[[files]]
file = "mods/Tianjin-Metro-1.0.0-beta-5+1.20.1.jar"
hash = "b7261acdb4012619addab8686eaf99df6f0deb8fed0709cd43cb1d4639a13471"

[[files]]
file = "mods/Xaeros_Minimap_25.2.0_Fabric_1.20(1).jar"
hash = "ee5580ace317e6cce7a102cd3c3f6b25d53fe0f57aa8857eacecaa9b277246cf"

[[files]]
file = "mods/airstrike_mod_fabric-1.0.0.jar"
hash = "ca34768a45245e6d022f9dd5a7547d26b67776281354b2e994f442661a30a7db"

[[files]]
file = "mods/architectury-9.2.14-fabric.jar"
hash = "bd7a7032bedb2ff96c6991a846a44c857336a51442a105f5859017e8ba9d1321"

[[files]]
file = "mods/brewinandchewin-3.0.6+1.20.1.jar"
hash = "98d700ae6261cc07d234ae9348abb0adca302c5682ebc71944f3b6ac429b482b"

[[files]]
file = "mods/c2me-fabric-mc1.20.1-0.2.0+alpha.11.16.jar"
hash = "a6c0f7fbc1b2a62cafe72a967165caeef0fb671b7e0d377bd60fbb1e7f724cde"

[[files]]
file = "mods/chefs-delight-1.0.3-fabric-1.20.1.jar"
hash = "c77994b4fc91aa416b5bea8a7c42e9b006803c9fe1d022e8c036fcf1b29d8331"

[[files]]
file = "mods/continuity-3.0.0+1.20.1.jar"
hash = "fdb646bd51667c57e576d1412c740ac48e3bf6953294dde11a62101a09395fe3"

[[files]]
file = "mods/corndelight-1.20.1-1.1.4.jar"
hash = "158498116f1bad39de974c0a4b7170b0ee4a8de4f000158ab82002ee8fba3b9c"

[[files]]
file = "mods/create-fabric-0.5.1-j-build.1631+mc1.20.1.jar"
hash = "33ec1d696c687e95cded0cffa6d581ac80bc9e416ec6040fcd595ce226d70bfb"

[[files]]
file = "mods/createmissiles-1.0.1+fabric-1.20.1-build.630.jar"
hash = "6855888db377611ce0b2c13291239d83a32dcc5642fde8a9333f879b70fe871f"

[[files]]
file = "mods/cullleaves-fabric-3.2.0.jar"
hash = "b85953d3c2de70f0fbd4cddf57f9c0861a9bd409077ce6e01da817f6e7584177"

[[files]]
file = "mods/cultural-delights-fabric-1.0.5+1.20.1.jar"
hash = "1ac651b63dec9218af57bbe05ef6e6ebafeeb897bfe98d0caeb5e7868e37e5a0"

[[files]]
file = "mods/enhancedblockentities-0.9+1.20.jar"
hash = "1c4ce2c00d8cc6d2269de3cadaba551607c62692a8e5ad1d7c618462ed7ed05b"

[[files]]
file = "mods/entityculling-fabric-1.7.4-mc1.20.1.jar"
hash = "ad938f570cf88c9a1a8e954999920cd718eb15f7b1de8b67d33046ef1f9a8507"

[[files]]
file = "mods/evenmoreinstruments-fabric-1.20-1.20.1-6.1.3.1.jar"
hash = "660c988be9a7a5cb0418cb78318af1c0a5da1e484ddb1a8e7e89e78cec82d34b"

[[files]]
file = "mods/fabric-api-0.92.2+1.20.1.jar"
hash = "4500f844c45573d039d68d3963c9885aa9de7712670216e0ad3e5df16c6770fc"

[[files]]
file = "mods/fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar"
hash = "87737ead3546a4f09c80ffa45d786cce2f3a49650ad9386c1a5a0439b0467f8a"

[[files]]
file = "mods/ferritecore-6.0.1-fabric.jar"
hash = "c7ba1118a05b2da900d1c369fbe1017a3e3ec3cafe5e51398b851279b9becf24"

[[files]]
file = "mods/geckolib-fabric-1.20.1-4.7.2.jar"
hash = "bc76fc3f61443db4da856502777c88ec62521d043f349da72105df172b065387"

[[files]]
file = "mods/genshinstrument-fabric-1.20-1.20.1-4.0.2.jar"
hash = "a05dbbc056742eb03a0e553f906ddc421b28a1618ea3f600a0e733d131f8e83f"

[[files]]
file = "mods/indium-1.0.34+mc1.20.1.jar"
hash = "33bdc7f01bdca61fd1d526e9e6ae1acdf107412ed0f6483da528d7eadc919059"

[[files]]
file = "mods/iris-1.7.5+mc1.20.1.jar"
hash = "95b870dfe225ff26d9d3997c0b0089063d3b6e0e017f018d7217f52a31076f08"

[[files]]
file = "mods/lithium-fabric-mc1.20.1-0.11.2.jar"
hash = "a0c595355d680e0c87bf8eaebafedff6900d4e771a8d6894ee6d2d4374de8df9"

[[files]]
file = "mods/minecraft-comes-alive-7.6.11+1.20.1-universal.jar"
hash = "b25cbe2eac216b15ff16c943b512b297e1f054f902771e829a7c51386106dec6"

[[files]]
file = "mods/modernfix-fabric-5.20.0+mc1.20.1.jar"
hash = "fb33b0a523e302e658bfe005c5ba1c765cd33f37e45f54880e8dce291b1954a7"

[[files]]
file = "mods/modmenu-7.2.2.jar"
hash = "a041b0f0305ffa5eb90120aa23768e1cfbb27583904b1751e3783c0f69382f1a"

[[files]]
file = "mods/music_player-fabric-1.20.1-2.7.0.316.jar"
hash = "60a1bbf88482bb099721fa8d9424ad310c4af72a1a0a0ca7d7dc8f76ce6405b6"

[[files]]
file = "mods/mysticsbiomes-fabric-1.20.1-3.4.3.jar"
hash = "0b4f7a7c8ea4c25ed79fbce30a99cb423d6a3c8c2de4893b6284beb64b35aa93"

[[files]]
file = "mods/oceansdelight-fdrf-fabric-1.0.2-1.20.jar"
hash = "c87de6e5cd772c65d5f79e8b8fcbe04e6bad0e29b5caffde1141c59e9fde2754"

[[files]]
file = "mods/resolution-control-plus-1.20-3.0.0.jar"
hash = "fd3f280498989b9dd220650106b1483b9065a78313ac5b164e88c62f31c2b009"

[[files]]
file = "mods/sodium-fabric-0.5.11+mc1.20.1.jar"
hash = "5413baaa260a2eadcee4221b8e7105a8e2a9b5b2c84b73f704f2740319aab7df"

[[files]]
file = "mods/sophisticatedbackpacks-1.20.1-3.21.2.1.81.jar"
hash = "6420719b231824fc68f1ae69d8a829b43ff0ee480dc34347889f43a45b6ad572"

[[files]]
file = "mods/sophisticatedcore-1.20.1-1.0.8.1.119.jar"
hash = "8f34b5fa06db1046d1ff43f05253f4b03abda2bb2041ad13320444606a205293"

[[files]]
file = "mods/templates-2.1.1+1.20.1.jar"
hash = "496534e85938d222fccf05defe89b833d1ab7fe4a81aaafb39951f1f7a0045dd"

[[files]]
file = "mods/trafficcraft-fabric-1.20.1-1.1.3.jar"
hash = "dfc2e9aaf9f81a3e4bc0c340c9df951a5730c3f667cb2bb46344c2cf191e34b2"

[[files]]
file = "mods/u_team_core-fabric-1.20.1-5.1.4.346.jar"
hash = "9661087b7fccbaa227334a67a5c771acdd9b9269660007122f470dd3e035db8f"

[[files]]
file = "mods/vanillabackport-fabric-1.20.1-1.1.4.3.jar"
hash = "b8a87f1be6ffb62bc8a1c948498112ffdc1ddaa6fc1eda8b6167a0353de62809"

[[files]]
file = "mods/wildlife-1.20.1-2.2.jar"
hash = "1bd5af612b5370626fbc645629c4c630d08c162a2301136f1304b5681f9b2092"

[[files]]
file = "mods/worldedit-mod-7.2.15.jar"
hash = "17db6b3e94f52d25426684663e1e1846823cbb7907f1c365ac329e5bc7bfaf2c"

[[files]]
file = "resourcepacks/MTRPackLDM.zip"
hash = "1454c4c18e4131b42ef236d1c977972cafb5e161d236f5651aeb79718962af9a"
